trivial updates

diff --git a/.config/lf/lfrc b/.config/lf/lfrc
--- a/.config/lf/lfrc
+++ b/.config/lf/lfrc
@@ -1,4 +1,6 @@
 set shell bash
+set shellopts '-eu'
+set ifs "\n"
 
 set mouse
 set hidden
@@ -8,14 +10,20 @@ set dircounts
 set dirfirst
 set number
 set relativenumber
+set scrolloff 4
 set wrapscroll false
 set ratios '1:3:4'
 
-map x trash
-map X $rm -rf "$fx"
+map Q :quit
+map D :delete
+map s shell
+# show the result of execution of previous commands
+map ` !true
+map m
+map mk :mkdir
+map f
+map ft :touch
 
-cmd q :quit
-cmd Q :quit
 cmd trash %set -f; trash $fx
 
 cmd open ${{
@@ -32,25 +40,37 @@ cmd open ${{
 }}
 
 cmd mkdir %{{
-    printf "directory name: "
-    read -r dirname
-    [[ -z "$dirname" ]] && printf "\033[1A\033[K" && exit 0
-    if [[ -e "$dirname" ]]; then
-        printf "Error: '%s' already exists\n" "$dirname"
-        exit 1
-    fi
-    mkdir -p "$dirname"
-    printf "\033[1A\033[K"
+  printf "mkdir "
+  read -r dirname
+  [[ -z "$dirname" ]] && printf "\033[1A\033[K" && exit 0
+  if [[ -e "$dirname" ]]; then
+    printf "Error: '%s' already exists\n" "$dirname"
+    exit 1
+  fi
+  mkdir -p "$dirname"
+  printf "\033[1A\033[K"
 }}
 
 cmd touch %{{
-    printf "file name: "
-    read -r filename
-    [[ -z "$filename" ]] && printf "\033[1A\033[K" && exit 0
-    if [ -e "$filename" ]; then
-        printf "Error: '%s' already exists\n" "$filename"
-        exit 1
-    fi
-    touch "$filename"
-    printf "\033[1A\033[K"
+  printf "touch "
+  read -r filename
+  [[ -z "$filename" ]] && printf "\033[1A\033[K" && exit 0
+  if [ -e "$filename" ]; then
+    printf "Error: '%s' already exists\n" "$filename"
+    exit 1
+  fi
+  touch "$filename"
+  printf "\033[1A\033[K"
+}}
+
+cmd extract ${{
+  set -f
+  case $f in
+    *.tar.bz|*.tar.bz2|*.tbz|*.tbz2) tar xjvf $f;;
+    *.tar.gz|*.tgz) tar xzvf $f;;
+    *.tar.xz|*.txz) tar xJvf $f;;
+    *.zip) unzip $f;;
+    *.rar) unrar x $f;;
+    *.7z) 7z x $f;;
+  esac
 }}
