shell: optimize shellrc to better work on macos and linux

diff --git a/.config/shell/shellrc b/.config/shell/shellrc
--- a/.config/shell/shellrc
+++ b/.config/shell/shellrc
@@ -1,20 +1,26 @@
+export HOMEBREW_NO_ENV_HINTS=1
+export HOMEBREW_NO_AUTO_UPDATE=1
+export HOMEBREW_NO_UPGRADE_AUTO_UPDATES_CASKS=1
+export HOMEBREW_NO_ANALYTICS=1
+# export HOMEBREW_NO_INSTALL_CLEANUP=1
+
 export LESS="--wordwrap --RAW-CONTROL-CHARS --incsearch --ignore-case --search-options=W --file-size --use-color --HILITE-UNREAD --status-column --mouse --wheel-lines=2 --quiet"
 export LESSCHARSET=utf-8
 
-eval "$(fzf --$(ps -p $$ -o comm=))"
-eval "$(zoxide init $(ps -p $$ -o comm=))"
-# eval $(thefuck --alias)
-# eval $(thefuck --alias fk)
-# eval "$(starship init $(ps -p $$ -o comm=))"
+_shell=$(ps -p $$ -o comm=)
+_shell=${${_shell##*/}#-}
+eval "$(fzf --$_shell)"
+eval "$(zoxide init $_shell)"
+unset _shell
 
 # Attach to tmux only when not attached yet
-if command -v tmux >/dev/null 2>&1 && [[ -z "$TMUX" ]] && (( SHLVL == 1 )); then
-    if ! tmux ls &> /dev/null; then
-        tmux new-session -s general
-    else
-        if [[ -z "$(tmux list-clients)" ]]; then
-            tmux attach-session
-        fi
+if [[ "$TERM_PROGRAM" != "vscode" && "$TERM_PROGRAM" != "zed" && "$TERMINAL_EMULATOR" != "JetBrains-JediTerm" ]] &&
+   command -v tmux >/dev/null 2>&1 &&
+   [[ -z "$TMUX" ]] && [[ -o interactive ]] && [[ -t 0 ]]; then
+    if ! tmux ls &>/dev/null; then
+        exec tmux new-session -s general
+    elif [[ -z "$(tmux list-clients 2>/dev/null)" ]]; then
+        exec tmux attach-session
     fi
 fi
 
@@ -67,10 +73,23 @@ function condainit() {
     fi
 }
 
-function nvminit() {
-    export NVM_DIR="$XDG_DATA_HOME/nvm"
-    [[ -f "/usr/share/nvm/init-nvm.sh" ]] && source /usr/share/nvm/init-nvm.sh
-}
+# Initialize nvm efficiently
+export NVM_DIR="$HOME/.nvm"
+[[ -s "$NVM_DIR/nvm.sh" ]] || NVM_DIR="$HOME/.local/share/nvm"
+_nvm_version=$(<"$NVM_DIR/alias/default")
+_nvm_version=${_nvm_version#v}
+export PATH="$NVM_DIR/versions/node/v$_nvm_version/bin:$PATH"
+unset _nvm_version
+_nvm_completion="$NVM_DIR/bash_completion"
+[ -s "$_nvm_completion" ] || _nvm_completion="${HOMEBREW_PREFIX-}/opt/nvm/etc/bash_completion.d/nvm"
+if [ -n "${ZSH_VERSION-}" ]; then
+  zsh-defer source "$NVM_DIR/nvm.sh" --no-use
+  [ -s "$_nvm_completion" ] && zsh-defer source "$_nvm_completion"
+else
+  source "$NVM_DIR/nvm.sh" --no-use
+  [ -s "$_nvm_completion" ] && source "$_nvm_completion"
+fi
+unset _nvm_completion
 
 # Change current working directory when exiting Yazi
 function yazicd() {
