change sh file indent to 4 and a bit script updates

diff --git a/.config/shell/shellrc b/.config/shell/shellrc
--- a/.config/shell/shellrc
+++ b/.config/shell/shellrc
@@ -1,37 +1,37 @@
 # Attach to tmux only when not attached yet
 if command -v tmux &>/dev/null && [[ -z "$TMUX" ]]; then
-  if ! tmux has-session -t general 2>/dev/null; then
-    tmux new-session -s general
-  elif [[ -z "$(tmux list-clients -t general 2>/dev/null)" ]]; then
-    tmux attach-session -t general
-  fi
+    if ! tmux has-session -t general 2>/dev/null; then
+        tmux new-session -s general
+    elif [[ -z "$(tmux list-clients -t general 2>/dev/null)" ]]; then
+        tmux attach-session -t general
+    fi
 fi
 
 # Setup fzf keybinding and fuzzy completion
 eval "$(fzf --$(ps -p $$ -o comm=))"
 if command -v fd >/dev/null 2>&1; then
-  export FZF_DEFAULT_COMMAND="fd --type file --hidden --exclude .git"
-  export FZF_ALT_C_COMMAND="fd --type directory --hidden"
+    export FZF_DEFAULT_COMMAND="command fd --type file --hidden --exclude .git --exclude node_modules --exclude .venv"
+    export FZF_ALT_C_COMMAND="command fd --type directory --hidden --exclude .git --exclude node_modules --exclude .venv"
 elif command -v find >/dev/null 2>&1; then
-  export FZF_DEFAULT_COMMAND="find . -type f -not -path '*/.git/*' -not -name '.git'"
-  export FZF_ALT_C_COMMAND="find . -type d"
+    export FZF_DEFAULT_COMMAND="command find -type f ! -path '*/\.*git*' ! -path '*/\.venv*' ! -path '*/node_modules*'"
+    export FZF_ALT_C_COMMAND="command find -type d ! -path '*/\.*git*' ! -path '*/\.venv*' ! -path '*/node_modules*'"
 fi
 export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
-export FZF_CTRL_T_OPTS="--reverse --height=60% --preview 'bat --line-range :500 {}' --walker-skip .git,node_modules"
+export FZF_CTRL_T_OPTS="--reverse --height=60% --preview 'command bat --line-range :500 {}' --walker-skip .git,node_modules"
 export FZF_CTRL_R_OPTS="--reverse --height 25% --scroll-off=0 --bind 'ctrl-y:execute-silent(echo -n {2..} | pbcopy)+abort'"
-export FZF_ALT_C_OPTS="--reverse --height=60% --preview 'eza --tree --color=always {} | head -200'"
+export FZF_ALT_C_OPTS="--reverse --height=60% --preview 'command tree -C -L1 {} | head -200'"
 # Advanced customization
 # - The first argument to the function is the name of the command.
 # - You should make sure to pass the rest of the arguments to fzf.
 _fzf_comprun() {
-  local command=$1
-  shift
-  case "$command" in
-    cd)           fzf --preview 'eza --tree --level=2 --color=always {} | head -200' "$@" ;;
-    export|unset) fzf --preview "eval 'echo $'{}"         "$@" ;;
-    ssh)          fzf --preview 'dig {}'                   "$@" ;;
-    *)            fzf --preview "bat --line-range :200 {}" "$@" ;;
-  esac
+    local command=$1
+    shift
+    case "$command" in
+        cd)           fzf --preview 'command eza --tree --level=2 --color=always {} | head -200' "$@" ;;
+        export|unset) fzf --preview "eval 'echo $'{}"         "$@" ;;
+        ssh)          fzf --preview 'dig {}'                   "$@" ;;
+        *)            fzf --preview "command bat --line-range :200 {}" "$@" ;;
+    esac
 }
 # Searching Git objects
 # Repo: https://github.com/junegunn/fzf-git.sh
@@ -52,41 +52,41 @@ eval "$(zoxide init $(ps -p $$ -o comm=))"
 # eval "$(starship init $(ps -p $$ -o comm=))"
 
 function condainit() {
-  local CONDA_BASE="$HOME/Programs"
-  if [[ -f "$CONDA_BASE/miniconda3/bin/activate" ]]; then
-    source "$CONDA_BASE/miniconda3/bin/activate"
-    return 0
-  elif [[ -f "$CONDA_BASE/anaconda3/bin/activate" ]]; then
-    source "$CONDA_BASE/anaconda3/bin/activate"
-    return 0
-  else
-    echo "Neither Miniconda nor Anaconda installation found in $CONDA_BASE"
-    return 1
-  fi
+    local CONDA_BASE="$HOME/Programs"
+    if [[ -f "$CONDA_BASE/miniconda3/bin/activate" ]]; then
+        source "$CONDA_BASE/miniconda3/bin/activate"
+        return 0
+    elif [[ -f "$CONDA_BASE/anaconda3/bin/activate" ]]; then
+        source "$CONDA_BASE/anaconda3/bin/activate"
+        return 0
+    else
+        echo "Neither Miniconda nor Anaconda installation found in $CONDA_BASE"
+        return 1
+    fi
 }
 
 function nvminit() {
-  export NVM_DIR="$HOME/.nvm"
-  [[ -s "$NVM_DIR/nvm.sh" ]] && \. "$NVM_DIR/nvm.sh"
-  [[ -s "$NVM_DIR/bash_completion" ]] && \. "$NVM_DIR/bash_completion"
+    export NVM_DIR="$HOME/.nvm"
+    [[ -s "$NVM_DIR/nvm.sh" ]] && \. "$NVM_DIR/nvm.sh"
+    [[ -s "$NVM_DIR/bash_completion" ]] && \. "$NVM_DIR/bash_completion"
 }
 
 # Change current working directory when exiting Yazi
 function yazicd() {
-  local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
-  yazi "$@" --cwd-file="$tmp"
-  if cwd="$(command cat -- "$tmp")" && [[ -n "$cwd" ]] && [[ "$cwd" != "$PWD" ]]; then
-    builtin cd -- "$cwd"
-  fi
-  rm -f -- "$tmp"
+    local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
+    yazi "$@" --cwd-file="$tmp"
+    if cwd="$(command cat -- "$tmp")" && [[ -n "$cwd" ]] && [[ "$cwd" != "$PWD" ]]; then
+        builtin cd -- "$cwd"
+    fi
+    rm -f -- "$tmp"
 }
 
 # Change current working directory when exiting Vifm
 function vifmcd() {
-  local dst="$(command vifm --choose-dir - "$@")"
-  if [[ -z "$dst" ]]; then
-    echo 'Directory picking cancelled/failed'
-    return 1
-  fi
-  cd "$dst"
+    local dst="$(command vifm --choose-dir - "$@")"
+    if [[ -z "$dst" ]]; then
+        echo 'Directory picking cancelled/failed'
+        return 1
+    fi
+    cd "$dst"
 }
diff --git a/.local/bin/vimawhr b/.local/bin/vimawhr
--- a/.local/bin/vimawhr
+++ b/.local/bin/vimawhr
@@ -7,33 +7,35 @@ set -euo pipefail
 # and copy content to clipboard after quitting
 # ------------------------------------------------------------------------------
 
-err() { echo -e "$@" 1>&2; }
+function err() {
+    echo -e "$@" 1>&2;
+}
 
 if ! command -v wl-copy >/dev/null 2>&1; then
-  err "wl-clipboard is not installed"
-  exit 1
+    err "wl-clipboard is not installed"
+    exit 1
 fi
 
 editors=("nvim" "vim" "vi")
 editor=""
 
 for e in "${editors[@]}"; do
-  if command -v "$e" >/dev/null 2>&1; then
-    editor="$e"
-    break
-  fi
+    if command -v "$e" >/dev/null 2>&1; then
+        editor="$e"
+        break
+    fi
 done
 
 if [[ -z "$editor" ]]; then
-  err "No suitable editor (nvim, vim, or vi) found"
-  exit 1
+    err "No suitable editor (nvim, vim, or vi) found"
+    exit 1
 fi
 
 while getopts ":v" opt; do
-  case "$opt" in
-    v) set -x ;;
-    *) err "Invalid option: -$OPTARG" >&2 ;;
-  esac
+    case "$opt" in
+        v) set -x ;;
+        *) err "Invalid option: -$OPTARG" >&2 ;;
+    esac
 done
 
 TMPFILE_DIR=/tmp/vim-anywhere
